DateFormat = "02.01.2006"
DatePublished = "Опубликовано %s"
DateUpdatedPublished = "Обновлено %s ・ Опубликовано %s"
FooterPoweredBy = 'Питается силой <a href="https://ddpub.org">DDPub</a>'
TagsTitle = "Теги"