address = "norikitech.com"

[notes]
id_format = '^\d{12}'
id_link_format = '^ยง(\d{12})$' # Include submatch

[feed]
tag = "norikitech_publish"

[[tags]]
tag = "books_tech"
slug = "books"
title = "Books"